keys:
  - &xun_host age1mkmnhfjvmck66llhu6drc5dv3rf6g7d2a5jt2jl0w4ehkey5wd4sqmyh5w
  - &workstation_host age107kcc8jyavcxu0kvdjmld8zwxsg0hwlxqe6rtczagsfnc3wdk9ysethz3w
creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
    - age:
      - *xun_host
      - *workstation_host
